apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mohamedtarekguezguez
  name: app-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
